const BAD_REQUEST_ERROR_CODE = 400;
const CAST_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const INT_SERVER_ERROR_CODE = 500;
const AUTHORIZATION_ERROR_CODE = 401;
const CONFLICT_ERROR_CODE = 409;
const FORBIDDEN_ERROR_CODE = 403;

module.exports = {
  BAD_REQUEST_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INT_SERVER_ERROR_CODE,
  CAST_ERROR_CODE,
  AUTHORIZATION_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
};
